import {useMemo,useRef,useState} from "react";
import type {CandidateRecord,InterviewReview,SheetPlayer} from "@/lib/sheets-client";
import {isUncertainWrite} from "@/lib/sheets-client";
import {valueAt} from "@/lib/management-data";
export const reviewCategories=["条件のずれ","事前確認不足","面談準備不足","仕事内容の認識違い","連絡・日程調整","募集枠・タイミング","他案件との比較","理由未確認","その他"];
type Advice={summary:string;actions:string[];count:number;generatedAt:string};
export function InterviewReviews({records,reviews,players,period,live,enabled,canWrite,onSave,onAnalyze}:{records:CandidateRecord[];reviews:InterviewReview[];players:SheetPlayer[];period:string;live:boolean;enabled:boolean;canWrite:boolean;onSave:(payload:unknown,id:string)=>Promise<unknown>;onAnalyze:(period:string)=>Promise<Advice>}) {
 const [selected,setSelected]=useState("");const [category,setCategory]=useState(reviewCategories[0]);const [memo,setMemo]=useState("");const [nextAction,setNextAction]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [thinking,setThinking]=useState(false);const [advice,setAdvice]=useState<Advice|null>(null);const [saved,setSaved]=useState(false);const operation=useRef(crypto.randomUUID());const pending=useRef<unknown>(null);
 const eligible=records.filter(r=>/^\d{4}-\d{2}-\d{2}$/.test(valueAt(r,17))&&!/^\d{4}-\d{2}-\d{2}$/.test(valueAt(r,22))&&!/^\d{4}-\d{2}-\d{2}$/.test(valueAt(r,24))&&(period==="all"||valueAt(r,17).startsWith(period)));
 const filtered=reviews.filter(r=>eligible.some(c=>c.recordId===r.recordId));const aggregate=reviewCategories.map(c=>({category:c,count:filtered.filter(r=>r.category===c).length})).filter(r=>r.count).sort((a,b)=>b.count-a.count);
 const fingerprint=useMemo(()=>JSON.stringify(aggregate),[aggregate]);const [adviceFingerprint,setAdviceFingerprint]=useState("");
 const open=(r:CandidateRecord)=>{if(pending.current||saving)return;const review=reviews.find(v=>v.recordId===r.recordId);setSelected(r.recordId);setCategory(review?.category||"理由未確認");setMemo(review?.memo||"");setNextAction(review?.nextAction||"");setError("");setSaved(false);operation.current=crypto.randomUUID();};
 const record=eligible.find(r=>r.recordId===selected);const review=reviews.find(r=>r.recordId===selected);
 return <div className="review-workspace"><section className="card review-heading"><div><span className="eyebrow">C面談から次の改善へ</span><h2>未マッチの振り返り</h2><p>合否待ちは未マッチと確定せず、理由が確認できた提案だけ記録してください。</p></div><div className="review-stat"><strong>{filtered.length}<small> / {eligible.length}</small></strong><span>理由記録済み / C面談後・未マッチ</span></div></section>
 {live&&!enabled&&<div className="info-box">Google側の振り返り機能を準備中です。接続コードの更新後に登録できます。</div>}
 <div className="review-columns"><section className="card review-panel"><h3>C面談後の提案</h3>{!eligible.length?<p className="panel-note">この期間に対象となる提案はありません。</p>:eligible.map(r=><button className={`review-candidate ${selected===r.recordId?"active":""}`} disabled={saving||!!pending.current} key={r.recordId} onClick={()=>open(r)}><div><strong>{r.candidateName}</strong><span>{valueAt(r,2)} · {players.find(p=>p.id===r.playerId)?.name}</span><span>C面談 {valueAt(r,17)} · {valueAt(r,7)}</span></div><span className="status-tag">{reviews.some(v=>v.recordId===r.recordId)?"理由記録済み":"未記録"}</span></button>)}</section>
 <section className="card review-panel"><h3>マッチしなかった理由</h3>{!record?<p className="panel-note">提案を選ぶと、理由と次回の対応を入力できます。</p>:<form onSubmit={async e=>{e.preventDefault();if(saving)return;setSaving(true);setError("");const payload=pending.current||{recordId:record.recordId,rowVersion:record.rowVersion,reviewVersion:review?.version||"",category,memo,nextAction};pending.current=payload;try{await onSave(payload,operation.current);pending.current=null;operation.current=crypto.randomUUID();setSaved(true);}catch(e){setError(e instanceof Error?e.message:"保存できませんでした。");if(!isUncertainWrite(e))pending.current=null;}finally{setSaving(false);}}}><p><strong>{record.candidateName}</strong> · {valueAt(record,2)}</p><fieldset disabled={saving||!!pending.current||!canWrite||!enabled}><label>主な理由<select value={category} onChange={e=>{setCategory(e.target.value);setSaved(false);}}>{reviewCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>詳しい理由・確認した事実<textarea value={memo} onChange={e=>{setMemo(e.target.value);setSaved(false);}} rows={5} maxLength={2000} placeholder="クライアント・本人から確認した内容、まだ確認できていないこと"/></label><label>次回の対応<textarea value={nextAction} onChange={e=>{setNextAction(e.target.value);setSaved(false);}} rows={3} maxLength={1000} placeholder="面談前に確認すること、担当者が次に行うこと"/></label></fieldset><p className="panel-note">詳しいメモは管理シートに保存し、AIには送りません。</p>{error&&<p role="alert" className="form-error">{error}</p>}{saved&&<p role="status">{live?"スプレッドシートに保存しました。":"サンプルに保存しました。"}</p>}<button className="primary-button" disabled={saving||!canWrite||!enabled}>{saving?"保存中…":pending.current?"同じ内容で再試行":"振り返りを保存"}</button></form>}</section></div>
 <section className="card review-panel"><div className="section-heading"><div><h3>理由の傾向と、次回へのアドバイス</h3><p className="panel-note">集計はC面談実施日で絞り込みます。後からマッチした提案は除外します。</p></div><button className="primary-button" disabled={thinking||!filtered.length||!enabled||!live} onClick={async()=>{setThinking(true);setError("");try{setAdvice(await onAnalyze(period));setAdviceFingerprint(fingerprint);}catch(e){setError(e instanceof Error?e.message:"AIの結果を取得できませんでした。");}finally{setThinking(false);}}}>{thinking?"AIが振り返り中…":"AIで改善案をまとめる"}</button></div><div className="review-bars">{aggregate.map(r=><div key={r.category}><span>{r.category}</span><progress max={filtered.length} value={r.count}/><strong>{r.count}件</strong></div>)}</div>{!filtered.length&&<p className="panel-note">理由を記録すると、ここに傾向が表示されます。</p>}<p className="panel-note">Googleに送る内容：上に表示した理由の分類と件数のみ。氏名・会社名・詳細メモは送信しません。Google無料枠の入力はサービス改善に利用されます。</p>{!live&&<p className="panel-note">サンプル画面ではAIを実行しません。</p>}{error&&!record&&<p role="alert" className="form-error">{error}</p>}{advice&&<div className="review-advice"><span className="eyebrow">AIによる改善の提案 · {advice.count}件の記録から</span>{adviceFingerprint!==fingerprint&&<p>記録が変わりました。再実行すると最新の集計を使います。</p>}<p>{advice.summary}</p><ol>{advice.actions.map((a,i)=><li key={i}>{a}</li>)}</ol><p className="panel-note">分類の集計からの提案です。詳細な原因はメモとクライアントへの確認をもとに判断してください。</p></div>}</section></div>;
}
