"use client";
import { useEffect, useRef, useState } from "react";
import { LayoutDashboard, Trophy, ListChecks, UserRound, Plus, CalendarDays, TrendingUp, UsersRound, BriefcaseBusiness, Handshake, Target, Sparkles, SlidersHorizontal, Monitor, LogOut, Search, ChevronRight, FileSpreadsheet, CheckCircle2, Copy, UserPlus, X, RefreshCw, Clock3 } from "lucide-react";
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarGroup } from "@/components/ui/sidebar";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxEmpty } from "@/components/ui/combobox";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { Progress } from "@/components/ui/progress";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { inputColumns } from "@/lib/sheets-schema";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { initialPlayers, makeDemoActivities, metricCount, rankPlayers, latestPlacements, stages, positions, statuses, statusForStage, inPeriod, type Activity, type Player, type Stage, type Metric } from "@/lib/node-data";

const today = "2026-10-04";
type View = "home" | "ranking" | "records" | "profile" | "players" | "connection";
const kpis: {label:string; stage:Stage; icon:typeof UsersRound; color:string}[] = [
 {label:"候補者面談",stage:"候補者面談",icon:UsersRound,color:"blue"},
 {label:"クライアントへの提案",stage:"提案",icon:BriefcaseBusiness,color:"mint"},
 {label:"クライアント面談",stage:"クライアント面談",icon:UserRound,color:"violet"},
 {label:"マッチ（候補者承諾）",stage:"内定承諾",icon:Handshake,color:"amber"},
];
function Picker({value,onChange,options,label,className=""}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string;className?:string}) {
 return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className={`app-select ${className}`}><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
function InsupLogo({className="",decorative=false}:{className?:string;decorative?:boolean}){return <img className={`insup-logo ${className}`} src={`${import.meta.env.BASE_URL}insup-logo-transparent.png`} alt={decorative?"":"Insup"} width={1226} height={1283}/>;}
function Avatar({player,small=false}:{player:Player;small?:boolean}){return <span className={`avatar ${player.color} ${small?"small-avatar":""}`}>{player.name.slice(0,1)}</span>}

export default function NodeWorkspace(){
 const [players,setPlayers]=useState(initialPlayers);
 const [activities,setActivities]=useState(makeDemoActivities);
 const [playerId,setPlayerId]=useState("ND-004");
 const [role,setRole]=useState<"player"|"admin">("player");
 const [view,setView]=useState<View>("home");
 const [periodMode,setPeriodMode]=useState("month");
 const [month,setMonth]=useState("2026-10");
 const [rankMetric,setRankMetric]=useState<Metric>("提案");
 const matchStage:Stage="内定承諾";
 const [recordOpen,setRecordOpen]=useState(false);
 const [detail,setDetail]=useState<Activity|null>(null);
 
 const [login,setLogin]=useState(false);
 const [playerDialog,setPlayerDialog]=useState(false);
 const [loginId,setLoginId]=useState("ND-004");
 const [search,setSearch]=useState("");
 const [stageFilter,setStageFilter]=useState("all");
 const [memberFilter,setMemberFilter]=useState("all");
 const [page,setPage]=useState(1);
 const player=players.find(p=>p.id===playerId)!;
 const admin=role==="admin";
 const period=periodMode==="today"?today:periodMode==="all"?"all":month;
 const periodLabel=periodMode==="today"?"今日":periodMode==="all"?"累計":`${Number(month.split("-")[1])}月`;
 const ranking=rankPlayers(players,activities,rankMetric,period);
 const proposalRanking=rankPlayers(players,activities,"提案",month);
 const me=proposalRanking.find(p=>p.id===playerId)!;
 const currentRanking=ranking.find(p=>p.id===playerId)!;
 const count=(stage:Metric,id:string|null=admin?null:playerId)=>metricCount(activities,id,stage,period);
 const nav=admin?[{id:"home",label:"全体ダッシュボード",icon:LayoutDashboard},{id:"ranking",label:"チームランキング",icon:Trophy},{id:"records",label:"人材・進捗管理",icon:ListChecks},{id:"players",label:"プレイヤー管理",icon:UsersRound},{id:"connection",label:"データ連携",icon:FileSpreadsheet}]:[{id:"home",label:"ダッシュボード",icon:LayoutDashboard},{id:"ranking",label:"ランキング",icon:Trophy},{id:"records",label:"成果・活動記録",icon:ListChecks},{id:"profile",label:"マイプロフィール",icon:UserRound}];
 const titles:Record<View,string>={home:admin?"NODE事業の成果":"ダッシュボード",ranking:"ランキング",records:admin?"人材・進捗管理":"成果・活動記録",profile:"マイプロフィール",players:"プレイヤー管理",connection:"データ連携"};
 const navigate=(next:View)=>{setView(next);setSearch("");setPage(1);};
 const toggleRole=()=>{setRole(admin?"player":"admin");navigate("home");};
 const placements=latestPlacements(activities,admin?(memberFilter==="all"?null:memberFilter):playerId);
 const filtered=placements.filter(a=>a.events.some(e=>inPeriod(e,period))&&(stageFilter==="all"||(a.status||statusForStage[a.stage])===stageFilter)&&`${a.candidateName} ${a.company} ${a.position} ${players.find(p=>p.id===a.playerId)?.name}`.toLowerCase().includes(search.toLowerCase()));
 const unproposed=[...new Map(activities.filter(a=>a.stage==="候補者面談"&&(admin?(memberFilter==="all"||a.playerId===memberFilter):a.playerId===playerId)&&inPeriod(a,period)&&!placements.some(p=>p.candidateId===a.candidateId)).map(a=>[a.candidateId,a])).values()];
 const rows=[...filtered,...unproposed.filter(a=>(stageFilter==="all"||stageFilter==="提案候補")&&`${a.candidateName} ${a.position}`.includes(search))];
 const visibleRows=rows.slice((page-1)*10,page*10);
 const latest=activities.filter(a=>(admin||a.playerId===playerId)&&inPeriod(a,period)).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id)).slice(0,5);
 const storeRecord=(a:Activity)=>{setActivities(prev=>[...prev,a]);setRecordOpen(false);setDetail(null);toast.success("プレビューに記録しました",{description:"成果・ランキングに反映されました。実シートへの保存は接続後に利用できます。"});};
 const stateRef=useRef({players,activities,period});stateRef.current={players,activities,period};
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:"read_node_ranking",title:"NODEランキングを確認",description:"現在の画面プレビューのランキングを読み取る。",inputSchema:{type:"object",properties:{metric:{type:"string",enum:["候補者面談","提案","クライアント面談","内定","内定承諾"]}},required:["metric"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){const m=(input as {metric?:Stage})?.metric;if(!m||!["候補者面談","提案","クライアント面談","内定","内定承諾"].includes(m))throw new Error("Unsupported metric");const s=stateRef.current;return {mode:"sample-preview",period:s.period,ranking:rankPlayers(s.players,s.activities,m,s.period).map(p=>({rank:p.rank,name:p.name,count:p.count}))};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);

 if(login)return <div className="login-page"><Toaster theme="light"/><div className="login-brand"><InsupLogo/><small>NODE</small></div><section className="login-card"><span className="login-symbol"><UserRound size={28}/></span><p className="eyebrow">PLAYER WORKSPACE</p><h1>あなたの成果を、ここに。</h1><p>プレイヤーIDでワークスペースを開きます。</p><form onSubmit={e=>{e.preventDefault();const found=players.find(p=>p.id.toUpperCase()===loginId.trim().toUpperCase());if(!found){toast.error("プレイヤーIDが見つかりません");return;}setPlayerId(found.id);setRole("player");navigate("home");setLogin(false);toast.success(`${found.name}さんの画面を開きました`);}}><label htmlFor="player-login">プレイヤーID</label><Input id="player-login" value={loginId} onChange={e=>setLoginId(e.target.value)} placeholder="ND-004" autoComplete="off" required/><button className="primary-button" type="submit">プレビューにログイン</button></form><div className="login-demo"><Sparkles size={17}/><div><strong>ログイン画面のプレビュー</strong><p>プレビューID：{players[0]?.id}〜{players.at(-1)?.id}。本番の本人確認は未接続です。</p></div></div><button className="text-button" onClick={()=>{setRole("admin");navigate("home");setLogin(false);}}>管理者画面をプレビュー</button></section><span className="login-footer">insup NODE · Performance Workspace</span></div>;

 const podium=(list:typeof ranking)=> <div className="podium">{[list[1],list[0],list[2]].filter(Boolean).map((p,i)=><div key={p.id} className={`podium-player podium-${i===1?"first":i===0?"second":"third"}`}><div className="podium-avatar-wrap">{i===1&&<Trophy className="winner-crown" size={22}/>}<Avatar player={p}/><span className="place-badge">{p.rank}</span></div><strong>{p.name}</strong><span className="podium-team">{p.team}</span><div className="podium-count">{p.count}<small>件</small></div><div className="podium-block"><span>{String(p.rank).padStart(2,"0")}</span></div></div>)}</div>;
 const rankRows=(list:typeof ranking,full=false)=> <div className="rank-list">{(full?list:list.filter(p=>p.id===playerId)).map(p=><div className={`rank-list-row ${p.id===playerId?"is-me":""}`} key={p.id}><span className="rank-order">{p.rank}</span><Avatar player={p}/><div className="rank-person"><strong>{p.name}{p.id===playerId&&<span className="you-tag">あなた</span>}</strong><span>{p.team}</span></div><div className="rank-bar"><div style={{width:`${list[0]?.count?p.count/list[0].count*100:0}%`}}/></div><span className="rank-total">{p.count}<small>件</small></span></div>)}</div>;

 return <SidebarProvider style={{"--sidebar-width":"244px"} as React.CSSProperties}><Toaster theme="light" position="top-center"/>
 <Sidebar className="app-sidebar"><SidebarHeader className="brand-block"><button onClick={()=>navigate("home")} className="brand" aria-label="Insup NODE ホーム"><InsupLogo decorative/><span className="brand-node">NODE</span></button><span className="workspace-label">PERFORMANCE WORKSPACE</span></SidebarHeader><SidebarContent><SidebarGroup><span className="nav-eyebrow">{admin?"管理者ワークスペース":"ワークスペース"}</span><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>navigate(n.id as View)} className="nav-button"><n.icon/><span>{n.label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><div className="sidebar-month"><span>{admin?"今月のチーム提案数":"今月のあなた"}</span><div><strong>{admin?metricCount(activities,null,"提案",month):me.rank}</strong><span>{admin?"件":"位"} <small>{!admin&&`/ ${players.length}人`}</small></span><Trophy/></div><p>{admin?"チームの活動を、成果につなげる。":"一つひとつの出会いが、成果に。"}</p></div></SidebarContent><SidebarFooter className="sidebar-bottom"><button onClick={toggleRole} className="role-switch"><SlidersHorizontal size={17}/>{admin?"プレイヤー画面へ":"管理画面をプレビュー"}</button><button onClick={()=>setLogin(true)} className="sidebar-user"><Avatar player={player}/><div><strong>{admin?"insup 管理者":player.name}</strong><span>{admin?"ADMIN PREVIEW":player.id}</span></div><LogOut size={16}/></button></SidebarFooter></Sidebar>
 <div className={`main-shell ${admin?"admin-shell":""}`}><header className="topbar"><div className="topbar-leading"><button className="mobile-brand" aria-label="Insup NODE ホーム" onClick={()=>navigate("home")}><InsupLogo decorative/></button><div className="breadcrumbs"><span className="desktop-breadcrumb">ワークスペース</span><span className="desktop-breadcrumb">/</span><strong>{titles[view]}</strong></div></div><div className="topbar-right"><span className="preview-chip">{admin?"管理者プレビュー":"画面プレビュー"}</span><button onClick={()=>setLogin(true)} aria-label="ログイン画面を開く"><Avatar player={player} small/></button></div></header><div className="demo-notice"><span><Sparkles size={15}/>成果・目標はサンプルデータ · 変更は再読み込みでリセット</span><button onClick={()=>navigate("connection")}>スプレッドシート未接続<ChevronRight size={13}/></button></div>
 <div className="admin-mobile-message"><Monitor size={38}/><h1>管理者画面はPCでご利用ください</h1><p>プレイヤー画面はスマートフォンから利用できます。</p><button onClick={toggleRole} className="primary-button">プレイヤー画面を開く</button></div>
 <main className="page-content"><div className="page-heading"><div><p className="eyebrow">{admin?"TEAM PERFORMANCE":view==="ranking"?"TEAM LEADERBOARD":"YOUR PERFORMANCE"}</p><h1>{titles[view]}{["home","ranking"].includes(view)&&<span className="heading-month">{month.replace("-",".")}</span>}</h1><p className="page-subtitle">{view==="home"?(admin?"チームの現在地と、一人ひとりの成果を確認。":`${player.name.split(" ")[0]}さん、今月の成果を確認しましょう。`):view==="ranking"?"一人ひとりの積み重ねを、チームの力に。":view==="records"?"面談から稼働開始まで、活動の流れを確認。":view==="players"?"メンバーのIDと目標を管理します。":view==="connection"?"今のスプレッドシートを、そのままデータの管理場所に。":"あなたの活動と成果を、ひとつのプロフィールに。"}</p></div>{!["players","connection","profile"].includes(view)&&<button className="primary-button" onClick={()=>{setDetail(null);setRecordOpen(true);}}><Plus size={19}/>成果を登録</button>}{view==="players"&&<button className="primary-button" onClick={()=>setPlayerDialog(true)}><UserPlus size={18}/>IDを発行</button>}</div>
 {["home","ranking","records"].includes(view)&&<div className="period-bar"><Tabs value={periodMode} onValueChange={v=>{setPeriodMode(v);setPage(1);}}><TabsList className="period-tabs"><TabsTrigger value="today">今日</TabsTrigger><TabsTrigger value="month">今月</TabsTrigger><TabsTrigger value="all">累計</TabsTrigger></TabsList></Tabs><div className="month-control"><CalendarDays size={16}/><Picker label="集計する月" value={month} onChange={v=>{setMonth(v);setPeriodMode("month");setPage(1);}} options={Array.from({length:15},(_,i)=>{const d=new Date(Date.UTC(2026,12-i,1));return {value:`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`,label:`${d.getUTCFullYear()}年${d.getUTCMonth()+1}月`};})}/></div></div>}
 {view==="home"&&<><div className="stats-grid">{kpis.map(m=><section className="stat-card" key={m.stage}><div className="stat-label">{m.stage==="内定承諾"?`マッチ（${matchStage}）`:m.label}<span className={`stat-icon ${m.color}`}><m.icon size={18}/></span></div><div className="stat-value">{count(m.stage==="内定承諾"?matchStage:m.stage)}<span>件</span></div><div className="stat-foot"><span>{periodMode==="today"?"10月4日の活動":periodMode==="all"?"すべての活動":`${Number(month.split("-")[1])}月の活動`}</span><TrendingUp size={14}/></div></section>)}</div>
 <div className="secondary-metrics"><div><CalendarDays size={18}/><span>C面談予約獲得</span><strong>{count("C面談予約")}<small>件</small></strong></div><div><Clock3 size={18}/><span>稼働開始予定</span><strong>{count("稼働開始予定")}<small>件</small></strong></div><div><CheckCircle2 size={18}/><span>稼働開始実績</span><strong>{count("稼働開始")}<small>件</small></strong></div></div><div className="dashboard-columns"><section className="card ranking-card"><div className="section-heading"><div><span className="eyebrow">TEAM LEADERBOARD</span><h2><Trophy size={21}/>{periodLabel}のランキング</h2></div><button onClick={()=>navigate("ranking")} className="text-button">すべて見る<ChevronRight size={16}/></button></div><div className="ranking-title"><strong>{rankMetric==="提案"?"クライアントへの提案数":rankMetric==="紹介人数"?"紹介した人材数":`${rankMetric}数`}</strong><span>{periodMode==="all"?"累計":periodLabel}</span></div>{podium(ranking)}{!admin&&rankRows(ranking)}<p className="ranking-note">同じ件数は同順位。集計ルールはデータ連携画面で確認。</p></section><div className="right-column">{!admin?<section className="goal-card"><div className="goal-top"><span className="eyebrow">MONTHLY GOAL</span><Target size={21}/></div><h2>{Number(month.split("-")[1])}月の提案目標</h2><div className="goal-number">{me.count}<span>/ {player.target} 件</span><strong>{Math.round(me.count/player.target*100)}%</strong></div><Progress value={Math.min(100,me.count/player.target*100)} className="goal-progress"/><p>{me.count>=player.target?"目標を達成しました！":<>目標まで、あと <strong>{player.target-me.count} 件</strong>。</>}</p><div className="goal-caption">一歩ずつ、着実に。</div></section>:<section className="goal-card"><div className="goal-top"><span className="eyebrow">TEAM PIPELINE</span><BriefcaseBusiness size={21}/></div><h2>人材の進捗</h2><div className="funnel">{["提案","クライアント面談",matchStage,"稼働開始"].map((s,i)=><div key={`${s}-${i}`}><span>{s==="内定"?"マッチ（内定）":s}</span><strong>{count(s as Stage)}<small>件</small></strong></div>)}</div><div className="goal-caption">各工程の日付で集計 · 延べ件数</div></section>}<section className="card quick-card"><span className="quick-icon"><Plus size={20}/></span><div><h3>{admin?"チームの進捗を確認":"今日の活動を記録"}</h3><p>{admin?"人材ごとの進捗と担当者を一覧に。":"面談や提案の成果を、その場で。"}</p></div><button className="secondary-button" onClick={()=>admin?navigate("records"):setRecordOpen(true)}>{admin?"人材・進捗管理を開く":"成果を登録"}</button></section></div></div>
 {admin&&<section className="card member-overview"><div className="section-heading"><h2>メンバーごとの成果</h2><span className="muted">{periodLabel} · {players.length}人</span></div><Table><TableHeader><TableRow><TableHead>プレイヤー</TableHead>{kpis.map(k=><TableHead key={k.stage}>{k.stage==="内定承諾"?"マッチ":k.stage}</TableHead>)}<TableHead>月間目標</TableHead></TableRow></TableHeader><TableBody>{players.map(p=><TableRow key={p.id}><TableCell><span className="table-person"><Avatar player={p} small/>{p.name}</span></TableCell>{kpis.map(k=><TableCell key={k.stage}>{count(k.stage==="内定承諾"?matchStage:k.stage,p.id)}</TableCell>)}<TableCell><div className="table-goal"><Progress value={Math.min(100,metricCount(activities,p.id,"提案",month)/p.target*100)}/><span>{p.target}件</span></div></TableCell></TableRow>)}</TableBody></Table></section>}
 <section className="card activity-preview"><div className="section-heading"><h2>最近の活動</h2><button onClick={()=>navigate("records")} className="text-button">活動を確認<ChevronRight size={16}/></button></div>{latest.length?latest.map(a=><button className="activity-row" key={a.id} onClick={()=>setDetail(a)}><span className="activity-dot"/><div><strong>{a.stage}</strong><span>{a.candidateName} {a.company&&`· ${a.company}`}{admin&&` · ${players.find(p=>p.id===a.playerId)?.name}`}</span></div><time>{a.date.replace(/-/g,".")}</time><span className="status-tag">記録済み</span></button>):<div className="empty-state">この期間の活動はまだありません。</div>}</section></>}
 {view==="ranking"&&<><div className="ranking-toolbar"><Picker label="ランキングの指標" value={rankMetric} onChange={v=>setRankMetric(v as Metric)} options={[{value:"紹介人数",label:"紹介した人材数（重複なし）"},{value:"C面談予約",label:"C面談予約獲得"},{value:"稼働開始予定",label:"稼働開始予定"},{value:"稼働開始",label:"稼働開始実績"},...kpis.map(k=>({value:k.stage==="内定承諾"?matchStage:k.stage,label:k.stage==="内定承諾"?`マッチ（${matchStage}）`:k.label}))]}/><span className="muted">{players.length}人のプレイヤー</span></div><section className="card full-ranking"><div className="section-heading"><h2><Trophy size={21}/>{rankMetric==="提案"?"クライアントへの提案":rankMetric}ランキング</h2><span className="muted">{periodLabel}</span></div>{podium(ranking)}{rankRows(ranking,true)}</section><div className="ranking-bottom"><span><Target size={18}/>あなたは <strong>{currentRanking.rank}位</strong> · {currentRanking.count}件</span><span>面談は候補者単位、提案以降は提案行単位で集計</span></div></>}
 {view==="records"&&<section className="card records-card"><div className="record-filters"><div className="search-control"><Search size={17}/><Input aria-label="候補者・会社名を検索" placeholder="候補者・会社名を検索" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div><Picker label="ステータスで絞り込み" value={stageFilter} onChange={v=>{setStageFilter(v);setPage(1);}} options={[{value:"all",label:"すべてのステータス"},...statuses.map(s=>({value:s,label:s}))]}/>{admin&&<Picker label="担当者で絞り込み" value={memberFilter} onChange={v=>{setMemberFilter(v);setPage(1);}} options={[{value:"all",label:"すべての担当者"},...players.map(p=>({value:p.id,label:p.name}))]}/>}</div><div className="list-caption"><strong>{rows.length}件の人材・提案</strong><span>選択した期間に活動のある人材を表示</span></div><div className="desktop-records"><Table><TableHeader><TableRow><TableHead>候補者</TableHead><TableHead>クライアント</TableHead><TableHead>ポジション</TableHead>{admin&&<TableHead>担当</TableHead>}<TableHead>ステータス</TableHead><TableHead>更新日</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visibleRows.map(a=><TableRow key={a.id}><TableCell><strong>{a.candidateName}</strong><span className="table-meta">{a.source}</span></TableCell><TableCell>{a.company||"未提案"}</TableCell><TableCell className="position-cell">{a.position}</TableCell>{admin&&<TableCell>{players.find(p=>p.id===a.playerId)?.name}</TableCell>}<TableCell><span className={`stage-tag stage-${stages.indexOf(a.stage)}`}>{a.status||statusForStage[a.stage]}</span></TableCell><TableCell>{a.date.replace(/-/g,".")}</TableCell><TableCell><button onClick={()=>setDetail(a)} className="text-button">詳細<ChevronRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table></div><div className="mobile-records">{visibleRows.map(a=><button key={a.id} className="mobile-record" onClick={()=>setDetail(a)}><div><strong>{a.candidateName}</strong><span className={`stage-tag stage-${stages.indexOf(a.stage)}`}>{a.status||statusForStage[a.stage]}</span></div><p>{a.company||"未提案"} · {a.position}</p><footer><span>{a.date.replace(/-/g,".")}</span><ChevronRight size={17}/></footer></button>)}</div>{!rows.length&&<div className="empty-state"><Search size={28}/><h3>該当する人材がありません</h3><p>期間や検索条件を変更してください。</p><button className="secondary-button" onClick={()=>{setSearch("");setStageFilter("all");setMemberFilter("all");setPeriodMode("all");}}>条件をリセット</button></div>}{rows.length>10&&<div className="pagination"><span>{(page-1)*10+1}〜{Math.min(page*10,rows.length)} / {rows.length}件</span><button disabled={page===1} onClick={()=>setPage(page-1)}>前へ</button><strong>{page} / {Math.ceil(rows.length/10)}</strong><button disabled={page*10>=rows.length} onClick={()=>setPage(page+1)}>次へ</button></div>}</section>}
 {view==="profile"&&<Profile player={player} count={s=>metricCount(activities,playerId,s,"all")} rank={me.rank} onSave={p=>{setPlayers(prev=>prev.map(x=>x.id===p.id?p:x));toast.success("プロフィールをプレビューに反映しました");}}/>}
 {view==="players"&&<section className="card"><div className="section-heading"><h2>プレイヤー一覧</h2><span className="muted">{players.length}人</span></div><p className="panel-note">登録メンバーのIDでプレイヤー画面を試せます。追加・編集内容は再読み込みでリセットされます。</p><Table><TableHeader><TableRow><TableHead>プレイヤー</TableHead><TableHead>ID</TableHead><TableHead>チーム</TableHead><TableHead>提案目標 / 月</TableHead><TableHead/></TableRow></TableHeader><TableBody>{players.map(p=><TableRow key={p.id}><TableCell><span className="table-person"><Avatar player={p} small/>{p.name}</span></TableCell><TableCell><code>{p.id}</code></TableCell><TableCell>{p.team}</TableCell><TableCell>{p.target}件</TableCell><TableCell><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(p.id);toast.success("IDをコピーしました");}catch{toast.info(`プレイヤーID：${p.id}`);}}}><Copy size={15}/>IDをコピー</button></TableCell></TableRow>)}</TableBody></Table></section>}
 {view==="connection"&&<div className="connection-layout"><section className="card connection-main"><span className="connection-symbol"><FileSpreadsheet size={30}/></span><h2>Googleスプレッドシート連携</h2><p>入力した内容を、既存のシートの対応する列に保存する構成です。</p><span className="connection-status"><Clock3 size={15}/>接続の設定待ち</span><div className="connection-steps"><div><span>1</span><div><strong>既存シートの項目を確認</strong><p>「2期目マッチングDB」と「2期目月間KPI・KGI」を確認済みです。</p></div></div><div><span>2</span><div><strong>画面の入力項目を列に対応づける</strong><p>元の形式と関数を維持して、入力列だけを書き込みます。</p></div></div><div><span>3</span><div><strong>本人確認と書き込みを接続</strong><p>プレイヤーは自分のデータ、管理者は全体を管理します。</p></div></div></div><details className="schema-details"><summary>確認済みの入力項目（19項目）</summary><div>{inputColumns.map(c=><span key={c.column}><code>{c.column}</code>{c.label}</span>)}</div></details><div className="sheet-links"><a href="https://docs.google.com/spreadsheets/d/1AnyvEoUtgUSTnuuJjIjA80XGHw_DaL9fSUoNCrYZ36s/edit?gid=286330650#gid=286330650" target="_blank" rel="noreferrer">指定のシート①を開く</a><a href="https://docs.google.com/spreadsheets/d/1AnyvEoUtgUSTnuuJjIjA80XGHw_DaL9fSUoNCrYZ36s/edit?gid=2007683505#gid=2007683505" target="_blank" rel="noreferrer">指定のシート②を開く</a></div><div className="info-box">元シートの形式を確認済みです。実データの連携と本番のログインは、まだ有効になっていません。C面談実施の集計参照（N列）と入力欄（Q列）の関係を接続前に確認します。</div></section><section className="card rule-card"><h2>集計ルール</h2><div className="rule-item"><strong>候補者面談</strong><p>面談実施日で集計。現行の重複除外に合わせ、同日・同担当・同候補者を1件として扱います。</p></div><div className="rule-item"><strong>提案・C面談</strong><p>各工程の日付で集計。提案行ごとに1件です。「紹介人数」は候補者の重複を除いた別指標です。</p></div><div className="rule-item"><strong>マッチの基準</strong><p>既存DBの「候補者承諾日＝マッチ日」に合わせて、内定承諾で集計します。</p><span className="status-tag">現在の基準：候補者承諾日</span></div><div className="rule-item"><strong>同順位と期間</strong><p>同じ件数は同順位。日付は日本時間の業務日として扱います。提案以降はDBの提案行単位です。</p></div><p className="panel-note">既存KPIの稼働開始は予定日を参照しています。実績は「稼働開始日」で別集計します。</p></section></div>}
 <footer className="page-footer"><span>insup NODE · Performance Workspace</span><div><button onClick={()=>setLogin(true)}>ログイン画面を見る</button><button className="mobile-role-switch" onClick={toggleRole}>管理者プレビュー</button></div></footer></main>
 {!admin&&<nav className="mobile-nav">{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>navigate(n.id as View)}><n.icon size={21}/><span>{n.id==="home"?"ホーム":n.id==="records"?"成果記録":n.id==="profile"?"プロフィール":n.label}</span></button>)}</nav>}</div>
 <RecordDialog open={recordOpen} onOpenChange={setRecordOpen} activities={activities} playerId={admin?(detail?.playerId||playerId):playerId} players={players} admin={admin} detail={detail} onSave={storeRecord}/>
 <Sheet open={!!detail&&!recordOpen} onOpenChange={open=>{if(!open)setDetail(null);}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{detail?.candidateName}</SheetTitle><SheetDescription>{detail?.company||"クライアント未提案"} · {detail?.position}</SheetDescription></SheetHeader>{detail&&<div className="detail-content"><div className="detail-info"><div><span>担当</span><strong>{players.find(p=>p.id===detail.playerId)?.name}</strong></div><div><span>紹介元</span><strong>{detail.source}</strong></div><div><span>候補者ID</span><code>{detail.candidateId}</code></div></div><div className="detail-status"><label>現在のステータス<Picker label="現在のステータス" value={detail.status||statusForStage[detail.stage]} onChange={v=>{setActivities(prev=>prev.map(a=>a.candidateId===detail.candidateId&&(a.recordId===detail.recordId||!detail.company)?{...a,status:v}:a));setDetail({...detail,status:v});toast.success("ステータスをプレビューに反映しました",{description:"登録済みの実績日付は維持されます。"});}} options={statuses.map(s=>({value:s,label:s}))}/></label></div><h3>活動のタイムライン</h3><div className="timeline">{stages.map(s=>{const event=activities.find(a=>a.candidateId===detail.candidateId&&a.stage===s&&(s==="候補者面談"||a.recordId===detail.recordId));return <div key={s} className={event?"done":""}><span>{event?<CheckCircle2 size={17}/>:<span className="timeline-circle"/>}</span><strong>{s}</strong><time>{event?event.date.replace(/-/g,"."):"未記録"}</time></div>;})}</div><button className="primary-button" onClick={()=>setRecordOpen(true)}><Plus size={18}/>この人材の活動を登録</button><div className="detail-extra">{detail.probability&&<p>ヨミ確度：{detail.probability}</p>}{detail.interviewScheduledDate&&<p>C面談予定：{detail.interviewScheduledDate} {detail.clientInterviewScheduledTime}</p>}{detail.memo&&<p className="detail-memo">メモ：{detail.memo}</p>}</div><p className="panel-note">プレビューの入力内容は実シートには保存されません。</p></div>}</SheetContent></Sheet>
 <Dialog open={playerDialog} onOpenChange={setPlayerDialog}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>プレイヤーIDを発行</DialogTitle><DialogDescription>新しいメンバーをプレビューに追加します。</DialogDescription></DialogHeader><form className="app-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=`ND-${String(Math.max(...players.map(p=>Number(p.id.slice(3))))+1).padStart(3,"0")}`;const p={id,name:String(f.get("name")).trim(),team:String(f.get("team")),target:Number(f.get("target")),color:"mint",bio:""};if(!p.name)return;setPlayers(prev=>[...prev,p]);setPlayerDialog(false);toast.success(`IDを発行しました：${id}`,{description:"このプレビュー内で利用できます。"});}}><label>名前<Input name="name" required maxLength={40} placeholder="例：山田 太郎"/></label><label>チーム<Input name="team" required maxLength={40} defaultValue="NODE"/></label><label>月間の提案目標<Input name="target" type="number" min="1" max="9999" defaultValue="20" required/></label><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setPlayerDialog(false)}>キャンセル</button><button className="primary-button">IDを発行</button></div></form></DialogContent></Dialog>
 </SidebarProvider>;
}

function Profile({player,count,rank,onSave}:{player:Player;count:(s:Stage)=>number;rank:number;onSave:(p:Player)=>void}){
 const [editing,setEditing]=useState(false);
 return <div className="profile-layout"><section className="card profile-card"><div className="profile-cover"><InsupLogo/><strong>NODE</strong></div><div className="profile-body"><Avatar player={player}/><h2>{player.name}</h2><p>{player.team}</p><span className="profile-id">PLAYER ID · {player.id}</span><p className="profile-bio">{player.bio||"プロフィールを登録してみましょう。"}</p><button className="secondary-button" onClick={()=>setEditing(true)}>プロフィールを編集</button></div></section><section className="card profile-performance"><span className="eyebrow">YOUR JOURNEY</span><h2>積み重ねてきた成果</h2><div className="profile-stats">{kpis.map(k=><div key={k.stage}><k.icon size={21}/><strong>{count(k.stage)}<small>件</small></strong><span>{k.label}</span></div>)}</div><div className="profile-rank"><Trophy size={24}/><div><strong>今月の提案ランキング {rank}位</strong><p>あなたの一件が、誰かの次の一歩に。</p></div></div></section><Dialog open={editing} onOpenChange={setEditing}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>プロフィールを編集</DialogTitle><DialogDescription>変更をプレビューに反映します。</DialogDescription></DialogHeader><form className="app-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!String(f.get("name")).trim()){toast.error("表示名を入力してください");return;}onSave({...player,name:String(f.get("name")).trim(),bio:String(f.get("bio")).trim(),target:Number(f.get("target"))});setEditing(false);}}><label>表示名<Input name="name" defaultValue={player.name} required maxLength={40}/></label><label>ひとこと<textarea name="bio" defaultValue={player.bio} maxLength={120} rows={3}/></label><label>月間の提案目標<Input type="number" name="target" defaultValue={player.target} min="1" max="9999" required/></label><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(false)}>キャンセル</button><button className="primary-button">変更を反映</button></div></form></DialogContent></Dialog></div>;
}

function RecordDialog({open,onOpenChange,activities,playerId,players,admin,detail,onSave}:{open:boolean;onOpenChange:(v:boolean)=>void;activities:Activity[];playerId:string;players:Player[];admin:boolean;detail:Activity|null;onSave:(a:Activity)=>void}){
 const [stage,setStage]=useState<Stage>("候補者面談");const [candidate,setCandidate]=useState<string|null>(null);const [owner,setOwner]=useState(playerId);const [position,setPosition]=useState(positions[0]);const [date,setDate]=useState(today);const [company,setCompany]=useState("");const [name,setName]=useState("");const [source,setSource]=useState("自社集客");const [newProposal,setNewProposal]=useState(false);const [probability,setProbability]=useState("Cヨミ");const [memo,setMemo]=useState("");const [interviewDate,setInterviewDate]=useState("");const [interviewTime,setInterviewTime]=useState("");const [error,setError]=useState("");
 useEffect(()=>{if(open){setOwner(playerId);setCandidate(detail?.candidateId||null);setStage(detail?stages[Math.min(stages.indexOf(detail.stage)+1,stages.length-1)]:"候補者面談");setPosition(detail?.position||positions[0]);setCompany(detail?.company||"");setName("");setSource(detail?.source||"自社集客");setDate(today);setNewProposal(false);setProbability(detail?.probability||"Cヨミ");setMemo(detail?.memo||"");setInterviewDate(detail?.interviewScheduledDate||"");setInterviewTime("");setError("");}},[open,detail,playerId]);
 const candidates=[...new Map(activities.filter(a=>a.playerId===owner).map(a=>[a.candidateId,a])).values()];
 const items=candidates.map(a=>({value:a.candidateId,label:`${a.candidateName} · ${a.candidateId}`}));
 const choice=items.find(a=>a.value===candidate)||null;
 const selected=candidates.find(a=>a.candidateId===candidate);
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="app-dialog record-dialog"><DialogHeader><DialogTitle>成果を登録</DialogTitle><DialogDescription>活動を記録すると、成果とランキングに反映されます。</DialogDescription></DialogHeader><form className="app-form" onSubmit={e=>{e.preventDefault();setError("");const candidateId=candidate||`C-PREVIEW-${crypto.randomUUID().slice(0,8)}`;const existing=candidates.find(a=>a.candidateId===candidate);const candidateName=existing?.candidateName||name.trim();if(candidateName.replace(/\s/g,"").length!==candidateName.length){setError("候補者氏名は、元シートのルールに合わせてスペースなしで入力してください。");return;}if(!candidateName){setError("候補者を選ぶか、候補者名を入力してください。");return;}if(!date||(stage!=="稼働開始予定"&&date>today)){setError("実績の日付は2026年10月4日まで、予定日は将来の日付を選べます。");return;}if(stage!=="候補者面談"&&!company.trim()){setError("クライアント名を入力してください。");return;}const targetCompany=stage==="候補者面談"?"":company.trim();const matching=activities.filter(a=>a.candidateId===candidateId&&a.company===targetCompany&&a.stage==="提案");if(stage!=="候補者面談"&&stage!=="提案"&&!detail&&new Set(matching.map(a=>a.recordId)).size>1){setError("同じ会社への提案が複数あります。一覧から対象の提案の詳細を開いて登録してください。");return;}const recordId=stage==="候補者面談"?undefined:stage==="提案"&&newProposal?`ROW-PREVIEW-${crypto.randomUUID()}`:detail?.company===targetCompany&&detail.recordId?detail.recordId:matching.at(-1)?.recordId||`ROW-PREVIEW-${crypto.randomUUID()}`;if(!(stage==="提案"&&newProposal)&&activities.some(a=>a.candidateId===candidateId&&a.stage===stage&&(stage==="候補者面談"?(a.playerId===owner&&a.date===date):a.recordId===recordId))){setError("この活動はすでに記録されています。別の工程を選んでください。");return;}const prior=activities.filter(a=>a.candidateId===candidateId&&(stage==="候補者面談"||a.recordId===recordId||a.stage==="候補者面談"));if(stage!=="稼働開始予定"&&prior.some(a=>a.stage!=="稼働開始予定"&&stages.indexOf(a.stage)<stages.indexOf(stage)&&a.date>date)){setError("前の工程より前の日付になっています。活動日を確認してください。");return;}if(stage!=="候補者面談"&&!existing){setError("候補者面談を先に登録し、候補者を選択してください。");return;}if(stages.indexOf(stage)>1&&!prior.some(a=>a.stage==="提案"&&a.company===targetCompany)){setError("このクライアントへの提案を先に登録してください。");return;}onSave({id:`PREVIEW-${crypto.randomUUID()}`,playerId:owner,recordId,candidateId,candidateName,source:existing?.source||source,company:targetCompany,position:existing?.position||position,stage,date,status:statusForStage[stage],probability,memo,interviewScheduledDate:interviewDate||undefined,clientInterviewScheduledTime:interviewTime||undefined});}}>
 <div className="form-grid"><label>活動の種類<Picker label="活動の種類" value={stage} onChange={v=>{setStage(v as Stage);setError("");}} options={stages.map(s=>({value:s,label:s==="提案"?"提案完了":s==="C面談予約"?"C面談予約獲得":s}))}/></label><label>活動日<Input type="date" value={date} max={stage==="稼働開始予定"?undefined:today} required onChange={e=>setDate(e.target.value)}/></label></div>
 {admin&&<label>担当者<Picker label="担当者" value={owner} onChange={v=>{setOwner(v);setCandidate(null);}} options={players.map(p=>({value:p.id,label:p.name}))}/></label>}
 <label>候補者<Combobox items={items} value={choice} onValueChange={v=>{setCandidate(v?.value||null);setError("");}} itemToStringLabel={item=>item.label}><ComboboxInput placeholder="登録済みの候補者を検索" aria-label="登録済みの候補者を検索" showClear/><ComboboxContent><ComboboxEmpty>候補者が見つかりません</ComboboxEmpty><ComboboxList>{(item:{value:string;label:string})=><ComboboxItem key={item.value} value={item}>{item.label}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></label>
 {stage==="候補者面談"&&!candidate&&<><label>新しい候補者名<Input value={name} onChange={e=>setName(e.target.value)} placeholder="サンプルの候補者名" maxLength={60} required/></label><div className="form-grid"><label>紹介元<Input value={source} onChange={e=>setSource(e.target.value)} maxLength={60} required/></label><label>ポジション<Picker label="ポジション" value={position} onChange={setPosition} options={positions.map(p=>({value:p,label:p}))}/></label></div></>}
 {stage!=="候補者面談"&&<label>クライアント名<Input value={company} onChange={e=>setCompany(e.target.value)} placeholder="例：クライアントA" maxLength={60} required/></label>}
 {stage==="提案"&&<label className="checkbox-label"><Checkbox checked={newProposal} onCheckedChange={v=>setNewProposal(v===true)}/>新しい提案行として登録（同じ候補者・会社への再提案）</label>}{selected&&<p className="selected-candidate">{selected.position} · 紹介元：{selected.source}</p>}
 {stage==="C面談予約"&&<div className="form-grid"><label>C面談予定日<Input type="date" value={interviewDate} onChange={e=>setInterviewDate(e.target.value)}/></label><label>C面談予定開始時刻<Input type="time" value={interviewTime} onChange={e=>setInterviewTime(e.target.value)}/></label></div>}{stage!=="候補者面談"&&<label>ヨミ確度<Picker label="ヨミ確度" value={probability} onChange={setProbability} options={[{value:"Aヨミ",label:"Aヨミ · 95％"},{value:"Bヨミ",label:"Bヨミ · 70％"},{value:"Cヨミ",label:"Cヨミ · 50％"},{value:"Dヨミ",label:"Dヨミ · 10％"}]}/></label>}<label>メモ<textarea value={memo} onChange={e=>setMemo(e.target.value)} rows={2} maxLength={500} placeholder="活動の補足（任意）"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="info-box"><Sparkles size={16}/>プレビュー用の入力です。個人情報は入力せず、サンプル名でお試しください。</div><div className="form-actions"><button type="button" className="secondary-button" onClick={()=>onOpenChange(false)}>キャンセル</button><button className="primary-button"><Plus size={17}/>記録して反映</button></div></form></DialogContent></Dialog>;
}
