"use client";
import { useEffect, useRef, useState } from "react";
import { FileSpreadsheet, RefreshCw, Search, Plus, LockKeyhole, Undo2, Pencil } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { useManagementSave, type ManagementMutation } from "./candidate-manager";
import { cellEditorValue, cellInputValue } from "@/lib/management-data";
import type { ManagementTable, ManagementTableInfo, ManagementRow } from "@/lib/sheets-client";
import "@/app/management.css";

type ReadManagement = <T>(action:"managementTables"|"managementTable",payload?:unknown)=>Promise<T>;
function colName(n:number):string {let name="";while(n>0){n--;name=String.fromCharCode(65+n%26)+name;n=Math.floor(n/26);}return name;}
function headerRow(title:string):number {return title==="目標"?0:/^マッチ計上/.test(title)?4:title==="1期目マッチングDB"||title==="稼働者管理表"?1:2;}
export function WorkbookManager({onRead,onSave,busy,canWrite}:{onRead:ReadManagement;onSave:ManagementMutation;busy:boolean;canWrite:boolean}) {
 const [tables,setTables]=useState<ManagementTableInfo[]>([]),[table,setTable]=useState<ManagementTable|null>(null),[id,setId]=useState<number|null>(null),[start,setStart]=useState(1),[search,setSearch]=useState(""),[showBlank,setShowBlank]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<ManagementRow|null>(null),[jump,setJump]=useState("1");
 const save=useManagementSave(onSave),serial=useRef(0),readRef=useRef(onRead);readRef.current=onRead;
 useEffect(()=>{let active=true;void readRef.current<{tables:ManagementTableInfo[]}>("managementTables").then(data=>{if(active){setTables(data.tables);setId(data.tables.find(t=>t.title==="案件管理表")?.sheetId??data.tables[0]?.sheetId??null);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function load(sheetId:number,row:number){const current=++serial.current;setLoading(true);setError("");setTable(null);try{const data=await readRef.current<ManagementTable>("managementTable",{sheetId,startRow:row});if(current===serial.current){setTable(data);setJump(String(row));}}catch(e){if(current===serial.current)setError(e instanceof Error?e.message:"管理表を取得できませんでした。");}finally{if(current===serial.current)setLoading(false);}}
 useEffect(()=>{if(id!==null){setSelected(null);void load(id,start);}return()=>{serial.current++;};},[id,start]);
 const headers=table?.rows.find(r=>r.row===headerRow(table.title)),columns=table?Array.from({length:table.columnCount},(_,i)=>({column:i+1,label:table.headers?.[i]||headers?.cells[i]?.display||colName(i+1)})):[];
 const visible=table?.rows.filter(r=>(showBlank||table.title==="目標"||r.cells.some(c=>c.display!==""))&&r.cells.some(c=>c.display.toLowerCase().includes(search.toLowerCase())))||[];
 const editable=(r:ManagementRow)=>!!table&&!table.readonly&&r.row>headerRow(table.title)&&canWrite;
 const blank=table?.rows.find(r=>editable(r)&&( /^マッチ計上/.test(table.title) ? !r.cells[5]?.value&&!r.cells.slice(1,11).some(c=>!c.readonly&&c.value!=="") : !r.cells[0]?.value&&!r.cells.some(c=>!c.readonly&&c.value!=="")));
 return <section className="workbook-manager"><div className="management-intro"><div><h2>業務管理表</h2><p>今までの管理表を、そのままアプリで確認・入力できます。</p></div><button className="secondary-button" disabled={busy||loading||id===null} onClick={()=>id!==null&&void load(id,start)}><RefreshCw size={16}/>再取得</button></div><div className="workbook-tabs">{tables.map(t=><button key={t.sheetId} className={id===t.sheetId?"selected":""} onClick={()=>{setId(t.sheetId);setStart(1);setSearch("");setShowBlank(false);}} disabled={save.busy||save.uncertain}><FileSpreadsheet size={15}/>{t.title}</button>)}</div>
  {error&&<div className="info-box" role="alert">{error}<button className="text-button" onClick={()=>id!==null&&void load(id,start)}>再試行</button></div>}{loading&&<div className="card management-loading" role="status">管理表を読み込んでいます…</div>}
  {table&&<div className="card workbook-card"><div className="management-filters"><strong>{table.title}</strong><label className="management-search"><Search size={16}/><input value={search} placeholder="表示中の50行を検索" aria-label="管理表の表示範囲を検索" onChange={e=>setSearch(e.target.value)}/></label><label className="management-check"><input type="checkbox" checked={showBlank} onChange={e=>setShowBlank(e.target.checked)}/>空の行も表示</label>{blank&&<button className="secondary-button" disabled={busy||save.busy} onClick={()=>setSelected(blank)}><Plus size={15}/>新しい行を入力</button>}</div>
  {table.readonly&&<div className="management-source-error"><LockKeyhole size={17}/><p>外部シートから取り込む集計表です。表示が #REF! の場合、Googleスプレッドシートで取り込み元へのアクセスを許可してください。取り込み結果は閲覧のみです。</p></div>}
  <div className="management-table-scroll"><table className="workbook-table"><thead><tr><th className="row-number">行</th>{columns.map(c=><th key={c.column}><span>{colName(c.column)}</span>{c.label}</th>)}<th/></tr></thead><tbody>{visible.map(r=><tr key={r.row}><th className="row-number">{r.row}</th>{r.cells.map(c=><td key={c.column} title={c.display||c.note}><button className={c.readonly?"computed-cell":"input-cell"} aria-label={`${r.row}行 ${columns[c.column-1]?.label} ${c.readonly?"自動計算":"編集"}`} disabled={!editable(r)||c.readonly||busy||save.busy} onClick={()=>setSelected(r)}>{c.readonly&&<LockKeyhole size={11}/>}<span>{c.display||"—"}</span></button></td>)}<td>{editable(r)&&<button className="text-button" disabled={busy||save.busy} onClick={()=>setSelected(r)}><Pencil size={14}/>編集</button>}</td></tr>)}</tbody></table></div>
  <div className="workbook-pagination"><span>{table.startRow}〜{Math.min(table.startRow+49,table.rowCount)}行 / {table.rowCount}行</span><button className="secondary-button" disabled={loading||start<=1} onClick={()=>setStart(Math.max(1,start-50))}>前へ</button><button className="secondary-button" disabled={loading||start+50>table.rowCount} onClick={()=>setStart(start+50)}>次へ</button><form onSubmit={e=>{e.preventDefault();const n=Number(jump);if(Number.isInteger(n)&&n>=1&&n<=table.rowCount)setStart(n);}}><input type="number" min={1} max={table.rowCount} value={jump} onChange={e=>setJump(e.target.value)} aria-label="表示する開始行"/><button className="text-button">行へ移動</button></form></div><p className="panel-note workbook-note">入力セルをクリックして編集できます。数式・自動表示・見出しを保護し、変更した入力だけ保存します。</p></div>}
  {save.undo&&<div className="management-undo"><span>直前の管理表の変更</span><button className="text-button" disabled={save.busy||busy} onClick={async()=>{await save.restore();if(id!==null)void load(id,start);}}><Undo2 size={15}/>元に戻す</button></div>}{save.error&&!selected&&<p className="form-error" role="alert">{save.error}</p>}
  {selected&&table&&<Dialog open onOpenChange={open=>{if(!open&&!save.busy&&!save.uncertain)setSelected(null);}}><DialogContent className="management-dialog"><DialogHeader><DialogTitle>{table.title} · {selected.row}行</DialogTitle><DialogDescription>変更した入力項目だけを保存します。計算結果は自動で更新されます。</DialogDescription></DialogHeader><WorkbookRowEditor key={`${table.sheetId}:${selected.row}`} row={selected} labels={columns.map(c=>c.label)} save={save} disabled={busy} onClose={()=>setSelected(null)} onSave={async changes=>{if(await save.save("saveManagementRow",{sheetId:table.sheetId,row:selected.row,rowVersion:selected.version,changes})){setSelected(null);if(id!==null)void load(id,start);}}}/></DialogContent></Dialog>}
 </section>;
}
function WorkbookRowEditor({row,labels,save,disabled,onClose,onSave}:{row:ManagementRow;labels:string[];save:ReturnType<typeof useManagementSave>;disabled:boolean;onClose:()=>void;onSave:(changes:Record<string,string|number|boolean>)=>Promise<void>}) {
 const [edited,setEdited]=useState<Record<string,string>>({}),[error,setError]=useState("");
 return <form onSubmit={e=>{e.preventDefault();try{const changes=Object.fromEntries(Object.entries(edited).filter(([col,v])=>v!==cellEditorValue(row.cells[Number(col)-1])).map(([col,v])=>[col,cellInputValue(row.cells[Number(col)-1],v)]));void onSave(changes);}catch(e){setError(e instanceof Error?e.message:"入力を確認してください。");}}}><fieldset disabled={disabled||save.busy||save.uncertain}><div className="record-field-grid">{row.cells.map(c=>{const text=edited[c.column]??cellEditorValue(c),label=labels[c.column-1]||colName(c.column);return <label key={c.column} className={text.length>160?"wide":""}><span>{label} <small>{colName(c.column)}{c.readonly&&" · 自動計算"}{c.kind==="percent"&&" · %"}</small></span>{c.readonly?<div className="readonly-field">{c.display||"—"}</div>:c.options.length?<select aria-label={label} value={text} onChange={e=>setEdited(p=>({...p,[c.column]:e.target.value}))}><option value="">未設定</option>{[...new Set([...c.options,...(text?[text]:[])])].map(o=><option key={o}>{o}</option>)}</select>:c.kind==="boolean"?<select aria-label={label} value={text} onChange={e=>setEdited(p=>({...p,[c.column]:e.target.value}))}><option value="true">はい</option><option value="false">いいえ</option></select>:text.length>160?<textarea aria-label={label} value={text} rows={4} maxLength={12000} onChange={e=>setEdited(p=>({...p,[c.column]:e.target.value}))}/>:<input aria-label={label} value={text} type={["date","time"].includes(c.kind)?c.kind:["number","percent"].includes(c.kind)?"number":"text"} step="any" maxLength={12000} onChange={e=>setEdited(p=>({...p,[c.column]:e.target.value}))}/>}</label>;})}</div></fieldset>{(error||save.error)&&<p className="form-error" role="alert">{error||save.error}</p>}<div className="form-actions"><button type="button" className="secondary-button" disabled={save.busy||save.uncertain} onClick={onClose}>閉じる</button><button className="primary-button" disabled={save.busy||disabled||!Object.keys(edited).length&&!save.uncertain}>{save.busy?"保存中…":save.uncertain?"同じ内容で再試行":"変更を保存"}</button></div></form>;
}
